In [1]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [2]:
X, y = make_blobs()

In [3]:
k=5
kmeans = KMeans(n_clusters=k, random_state=42) 
y_pred = kmeans.fit_predict(X)

In [4]:
y_pred

array([1, 0, 4, 2, 2, 2, 2, 3, 1, 1, 0, 3, 1, 2, 3, 0, 3, 2, 2, 3, 4, 4,
       3, 1, 1, 2, 1, 2, 3, 4, 2, 1, 1, 2, 0, 2, 3, 0, 2, 2, 1, 1, 2, 2,
       2, 1, 2, 1, 0, 0, 0, 2, 1, 4, 1, 4, 1, 1, 3, 2, 2, 2, 1, 2, 4, 3,
       1, 3, 2, 2, 1, 1, 1, 1, 3, 0, 0, 2, 1, 0, 0, 2, 1, 2, 2, 4, 1, 1,
       1, 1, 4, 1, 1, 2, 1, 2, 2, 2, 1, 3], dtype=int32)

In [5]:
y_pred is kmeans.labels_

True

In [6]:
kmeans.cluster_centers_

array([[ 8.47170087,  4.25814198],
       [ 3.09215506, -9.46228323],
       [-3.35392594,  4.04091241],
       [ 9.65664069,  3.34632583],
       [ 7.80059934,  2.67419294]])

In [7]:
import numpy as np

In [8]:
X_new = np.array([[0,2],[3,2],[-3,3],[-3,2.5]])

In [9]:
kmeans.predict(X_new)

array([2, 4, 2, 2], dtype=int32)

In [10]:
kmeans.transform(X_new).round(2)

array([[ 8.77, 11.87,  3.93,  9.75,  7.83],
       [ 5.92, 11.46,  6.67,  6.79,  4.85],
       [11.54, 13.87,  1.1 , 12.66, 10.81],
       [11.61, 13.42,  1.58, 12.68, 10.8 ]])

In [11]:
good_init = np.array([[-3,3], [-3,2], [-3,1], [-1,2], [0,2]])
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1, random_state=42)
kmeans.fit(X)

,n_clusters,5
,init,"array([[-3, ... [ 0, 2]])"
,n_init,1
,max_iter,300
,tol,0.0001
,verbose,0
,random_state,42
,copy_x,True
,algorithm,'lloyd'


In [12]:
kmeans.inertia_

117.91274835707056

In [13]:
kmeans.score(X)

-117.91274835707054

In [14]:
from sklearn.cluster import MiniBatchKMeans

In [15]:
minibatch_kmeans = MiniBatchKMeans(n_clusters=5, random_state=42) 
minibatch_kmeans.fit(X)

,n_clusters,5
,init,'k-means++'
,max_iter,100
,batch_size,1024
,verbose,0
,compute_labels,True
,random_state,42
,tol,0.0
,max_no_improvement,10
,init_size,None
,n_init,'auto'


In [16]:
import matplotlib.pyplot as plt

In [26]:
from sklearn.metrics import silhouette_score

In [27]:
silhouette_score(X, kmeans.labels_)

0.5054767384158236